export const data = [
  { name: "Bob Barber", age: 23, web_url: "./cards.html" },
  { name: "Alice Wonderland", age: 21, web_url: "./cards.html" },
];
export const unisData = [
  {
    country: "United States",
    name: "Marywood University",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["marywood.edu"],
    web_pages: "http://www.marywood.edu",
  },
  {
    country: "United States",
    name: "Lindenwood University",
    alpha_two_code: "US1em",
    "state-province": null,
    domains: ["lindenwood.edu"],
    web_pages: ["http://www.lindenwood.edu/"],
  },
  {
    country: "United States",
    name: "Sullivan University",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["sullivan.edu"],
    web_pages: ["https://sullivan.edu/"],
  },
  {
    country: "United States",
    name: "Florida State College at Jacksonville",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["fscj.edu"],
    web_pages: ["https://www.fscj.edu/"],
  },
  {
    country: "United States",
    name: "Xavier University",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["xavier.edu"],
    web_pages: ["https://www.xavier.edu/"],
  },
  {
    country: "United States",
    name: "Tusculum College",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["tusculum.edu"],
    web_pages: ["https://home.tusculum.edu/"],
  },
  {
    country: "United States",
    name: "Marywood University",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["marywood.edu"],
    web_pages: "http://www.marywood.edu",
  },
  {
    country: "United States",
    name: "Lindenwood University",
    alpha_two_code: "US1em",
    "state-province": null,
    domains: ["lindenwood.edu"],
    web_pages: ["http://www.lindenwood.edu/"],
  },
  {
    country: "United States",
    name: "Sullivan University",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["sullivan.edu"],
    web_pages: ["https://sullivan.edu/"],
  },
  {
    country: "United States",
    name: "Florida State College at Jacksonville",
    alpha_two_code: "US",
    "state-province": null,
    domains: ["fscj.edu"],
    web_pages: ["https://www.fscj.edu/"],
  },
];
